config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'static#splash', as: :unauthenticated_root
  end

  resources :entities
  resources :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :group
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :group_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups
  has_many :entities, foreign_key: 'author_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true, if: :will_save_change_to_email?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
  end

  def new
    @categories = Group.all.where(user_id: current_user.id)
    @entity = Entity.new
  end

  def create
    @entity = current_user.entities.new(entity_params)
    if @entity.save
      redirect_to group_path(entity_params[:group_id])
    else
      # Handle validation errors or other issues with saving
      flash[:error] = 'There was an error creating the new transaction, please try again.'
      render :new
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @categories = current_user.groups
  end

  def new
    @group = Group.new(user: current_user)
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def show
    @category = Group.find(params[:id])
    @transactions = @category.entities.order('created_at DESC')
    @icon = @category.icon
    @total_amount = @transactions.sum(&:amount)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = current_user.groups
    render 'groups/index'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authenticate_user!

  def splash
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/entities/new.html.erb
<head>
  <%= stylesheet_link_tag 'devise/login_and_registration' %>
</head>
<body>
  <div class="md:flex h-full">
    <div class="md:text-2xl font-bold text-dark flex gap-2 absolute p-5 md:right-0">
      <%= link_to '< Back', groups_path %>
    </div>
    <div class="w-1/2 h-full hidden md:block login-div">
      <!-- <%= image_tag 'login-bg.jpg', class: "h-full w-full" %> -->
    </div>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 w-full md:w-1/2 lg:w-1/2">
      <div class="sm:mx-auto sm:w-full sm:max-w-sm">
        <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-dark">Create a new Transaction</h2>
      </div>
    
      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    
        <div class="space-y-6" action="#" method="POST">
          <%= form_with(model: @entity, url: entities_path) do |form| %>
            <div>
              <%= form.label :name, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.text_field :name, placeholder: 'McDonalds',class: "block mt-2 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>              
            </div>

            <div>
              <%= form.label :amount, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.text_field :amount, placeholder: '10$', class: "block mt-2 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
            </div>
            
            <div>
              <%= form.label :select_category, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.select :group_id, options_from_collection_for_select(current_user.groups, 'id', 'name'), { prompt: 'Select a group' }, class: "block mt-2 w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
            </div>

            <div class="mt-4">
              <%= form.submit 'Create Transaction', class: 'flex transition-all w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/groups/_new_form.html.erb
<!-- <%= render "devise/shared/links" %> -->
<head>
  <%= stylesheet_link_tag 'devise/login_and_registration' %>
</head>
<body>
  <div class="flex h-full">
    <div class="w-1/2 h-full hidden md:block login-div">
      <!-- <%= image_tag 'login-bg.jpg', class: "h-full w-full" %> -->
    </div>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 w-full md:w-1/2 lg:w-1/2 bg-gray-100">
      <div class="sm:mx-auto sm:w-full sm:max-w-sm">
        <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-dark">Create a new Category</h2>
      </div>
    
      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    
        <div class="space-y-6" action="#" method="POST">
          <%= form_with(model: @group, url: groups_path) do |form| %>
            <div>
              <%= form.label :name, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.text_field :name, required: true, class: "block mt-2 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
            </div>

            <div>
              <%= form.label :icon, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.text_field :icon, required: true, class: "block mt-2 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
            </div>

            <div>
              <%= form.submit 'Create new Category', class: 'flex transition-all w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/groups/index.html.erb
<h1 class="text-3xl font-bold text-center text-dark m-2 lg:text-5xl md:text-5xl">Categories</h1>
<% if @categories.empty? %>
  <p class="border-2 p-2 m-6 rounded-sm text-center md:text-2xl lg:text-3xl text-gray-500">No categories created yet</p>
<% else %>
  <div class="m-4 p-4 border-4 rounded-sm">
    <% @categories.each_with_index do |category, index| %>
    <div class="border-2 p-2 my-4 rounded-sm flex justify-between <%= 'bg-gray-100' if index.even? %> ">
      <div class="flex flex-col w-12 md:w-14 lg:w-[4.5rem]">
        <h2 class="md:text-2xl lg:text-3xl font-bold text-primary border-b-2"><%= link_to category.name, category %></h2>
        <%= image_tag( "icons/#{category.icon}", class: 'w-full' )%>
      </div>
      <div class="flex flex-col justify-between text-right text-gray-500">
        <p>Transactions: <%= category.entities.count %></p>
        <p>
          <% @string = "#{category.created_at}" %>
          <% @time_object = Time.parse(@string) %>
          <%= @time_object.strftime('%d-%m-%Y') %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
<div class="flex justify-center pb-5">
  <%= link_to new_group_path, class: "group relative inline-block overflow-hidden rounded-2xl custom-background transition-all duration-300 text-lg font-bold custom-text p-3" do %>
    Create a new Category
  <% end %>
</div>

app/views/groups/new.html.erb
<head>
  <%= stylesheet_link_tag 'devise/login_and_registration' %>
</head>
<body>
  <div class="md:flex h-full">
    <div class="md:text-2xl font-bold text-dark flex gap-2 absolute p-5 md:right-0">
      <%= link_to '< Back', groups_path %>
    </div>
    <div class="w-1/2 h-full hidden md:block login-div">
      <!-- <%= image_tag 'login-bg.jpg', class: "h-full w-full" %> -->
    </div>
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 w-full md:w-1/2 lg:w-1/2">
      <div class="sm:mx-auto sm:w-full sm:max-w-sm">
        <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-dark">Create a new Category</h2>
      </div>
    
      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    
        <div class="space-y-6" action="#" method="POST">
          <%= form_with(model: @group, url: groups_path) do |form| %>
            <div>
              <%= form.label :name, class: "block text-sm font-medium leading-6 text-dark" %>
              <%= form.text_field :name, required: true, placeholder: 'Food',class: "block mt-2 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
            </div>

            <div class="mt-4">
              <div class="">
                <%= form.label :icon, class: "block text-sm font-medium leading-6 text-dark" %>
                <%= form.select :icon, %w[food entertainment education health_care housing personal_care], {}, { class: "block mt-2 w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
              </div>
            </div>

            <div class="mt-4">
              <%= form.submit 'Create new Category', class: 'flex transition-all w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/groups/show.html.erb
<div class="shadow-lg p-3 flex justify-center">
  <p class="md:text-2xl text-gray-500">Total Spent: <%= @total_amount %>$</p>
</div>
<h1 class="text-3xl font-bold text-center text-dark m-2 lg:text-5xl md:text-4xl"><%= @category.name %> Category</h1>
<% if @transactions.empty? %>
  <p class="border-2 p-2 m-6 rounded-sm text-center md:text-2xl lg:text-3xl text-gray-500">No transactions created yet</p>
<% else %>
  <div class="m-4 p-4 border-4 rounded-sm">
    <% @transactions.each do |transaction| %>
    <div class="border-2 p-2 my-4 rounded-sm flex justify-between">
      <div class="flex flex-col w-12 md:w-14 lg:w-[4.5rem]">
        <h2 class="md:text-2xl lg:text-3xl font-bold text-dark border-b-2"><%= transaction.name %></h2>
        <%= image_tag( "icons/#{@icon}", class: 'w-full' )%>
      </div>
      <div class="flex flex-col justify-between text-right">
        <p class="text-gray-600"><%= transaction.amount %>$</p>
        <p class="text-gray-600">
          <% @string = "#{transaction.created_at}" %>
          <% @time_object = Time.parse(@string) %>
          <%= @time_object.strftime('%d-%m-%Y') %>
        </p>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
<div class="flex justify-center pb-5">
  <%= link_to new_entity_path, class: "group relative inline-block overflow-hidden rounded-2xl custom-background text-lg font-bold custom-text p-3" do %>
    Create a new Transaction
  <% end %>
</div>

app/views/home/index.html.erb
<h1 class="text-3xl font-bold">
  Hello world!
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'app' %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="h-full">
    <% unless (controller_name == 'registrations' || controller_name == 'sessions' || controller_name == 'static' || !user_signed_in?) || (controller_name == 'groups' && action_name == 'new') || (controller_name == 'entities' && action_name == 'new') %>
      <%= render 'shared/navbar' %> <!-- Render navbar for other actions -->
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header class="bg-primary">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to 'WalletWizard', authenticated_root_path, class: "-m-1.5 p-1.5 font-bold text-white text-3xl" %>
    </div>
    <div class="flex lg:hidden">
      <button onclick="openMenu()" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-white">
        <span class="sr-only">Open main menu</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>
    <% if user_signed_in? %>
      <div class="hidden lg:flex lg:gap-x-12">
        <%= link_to 'Categories', groups_path,class: "font-semibold leading-6 text-white/75 hover:underline hover:scale-110 transition-all" %>
      </div>
    <% end %>
    <div class="hidden lg:flex lg:flex-1 lg:justify-end">
      <% if user_signed_in? %>
        <%= form_tag(destroy_user_session_path, method: :delete) do %>
          <%= submit_tag 'Log Out', class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold bg-[#fff] leading-7 text-dark hover:bg-dark hover:text-white cursor-pointer transition-all" %>
        <% end %>
      <% else %>
        <div class="flex gap-6">
          <%= link_to 'Log In', new_user_session_path, class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-primary cursor-pointer transition-all" %>

          <%= link_to 'Sign Up', new_user_registration_path, class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-primary cursor-pointer transition-all" %>
        </div>
      <% end %>
      <!-- <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50" %> -->
      <!-- <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a> -->
    </div>
  </nav>
  <!-- Mobile menu, show/hide based on menu open state. -->
  <div class="lg:hidden" role="dialog" aria-modal="true">
    <!-- Background backdrop, show/hide based on slide-over state. -->
    <div class="fixed inset-0 z-10 hidden mobile-menu-container"></div>
    <div class="fixed hidden inset-y-0 right-0 z-10 mobile-menu w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
      <div class="flex items-center justify-between">
        <%= link_to 'WalletWizard', authenticated_root_path, class: "text-dark font-bold text-2xl" %>
        <button type="button" onclick="closeMenu()" class="-m-2.5 rounded-md p-2.5 text-gray-800">
          <span class="sr-only">Close menu</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="mt-6 h-full">
        <div class="-my-6 divide-y divide-gray-500 flex flex-col justify-between h-full">
          <div class="space-y-2 py-6">
            <%= link_to 'Categories', groups_path, class: "-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-100" %>
          </div>
          <div class="py-6">
            <%= form_tag(destroy_user_session_path, method: :delete) do %>
              <%= submit_tag 'Logout', class: "block cursor-pointer w-full bg-gray-100 rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-200" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<script>
  const mobileMenu = document.querySelector('.mobile-menu');
  const mobileMenuContainer = document.querySelector('.mobile-menu-container');
  const openMenu = () => {
    mobileMenu.classList.remove('hidden');
    mobileMenuContainer.classList.remove('hidden');
  }

  const closeMenu = () => {
    mobileMenu.classList.add('hidden');
    mobileMenuContainer.classList.add('hidden');
  }
</script>